apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app: sysdig-agent
    app_group: sysdig-agent-app
  namespace: devops-sysdig
  name: sysdig-agent-app
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app_group: sysdig-agent-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sysdig-agent
        app_group: sysdig-agent-app
    spec:
      containers:
      - image: sysdig/agent
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - test
            - -e
            - /opt/draios/logs/running
          failureThreshold: 6
          initialDelaySeconds: 600
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: sysdig-agent
        readinessProbe:
          exec:
            command:
            - test
            - -e
            - /opt/draios/logs/running
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "3"
            memory: 2Gi
          requests:
            cpu: "2"
            memory: 2Gi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host/var/run/docker.sock
          name: docker-sock
        - mountPath: /host/dev
          name: dev-vol
        - mountPath: /host/proc
          name: proc-vol
          readOnly: true
        - mountPath: /host/boot
          name: boot-vol
          readOnly: true
        - mountPath: /host/lib/modules
          name: modules-vol
          readOnly: true
        - mountPath: /host/usr
          name: usr-vol
          readOnly: true
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /opt/draios/etc/kubernetes/config
          name: sysdig-agent-config
        - mountPath: /opt/draios/etc/kubernetes/secrets
          name: sysdig-agent-secrets
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      hostPID: true
      nodeSelector:
        region: app
        sysdig-agent: "true"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: sysdig-agent
      serviceAccountName: sysdig-agent
      terminationGracePeriodSeconds: 5
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - emptyDir:
          medium: Memory
        name: dshm
      - hostPath:
          path: /var/run/docker.sock
          type: ""
        name: docker-sock
      - hostPath:
          path: /dev
          type: ""
        name: dev-vol
      - hostPath:
          path: /proc
          type: ""
        name: proc-vol
      - hostPath:
          path: /boot
          type: ""
        name: boot-vol
      - hostPath:
          path: /lib/modules
          type: ""
        name: modules-vol
      - hostPath:
          path: /usr
          type: ""
        name: usr-vol
      - configMap:
          defaultMode: 420
          name: sysdig-agent-app
          optional: true
        name: sysdig-agent-config
      - name: sysdig-agent-secrets
        secret:
          defaultMode: 420
          secretName: sysdig-agent
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
