apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: |-
      Template for creating custom resource for Artifactory
  name: artifactory-cr-template
objects:
- apiVersion: artifactoryrepo.operators.bcgov/v1alpha1
  kind: ArtifactoryRepo
  metadata:
    name: ${TEAM_NAME}-${REPO_TYPE}-${REPO_LOCATOR}
  spec:
    # Add fields here: team-type-environment-locator
    console: ${CONSOLE_NAME}
    team_name: ${TEAM_NAME}
    repository_type: ${REPO_TYPE}
    repository_locator: ${REPO_LOCATOR}
    repository_description: ${REPO_DESCRIPTION}
    list_virtual_repositories: ${LIST_REPOS_VIRTUAL}
    user: ${USER}
parameters:
- description: Cluster where the CR is being created (choose between "lab" or "prod"
  displayName: Console Name
  name: CONSOLE_NAME
  value: lab
- description: Team name for the repository
  displayName: Team name
  name: TEAM_NAME
  value: qa
- description: Type of repository (choose between docker, maven etc)
  displayName: Team name
  name: REPO_TYPE
  value: docker
- description: Repository locator (choose between local or virtual)
  displayName: Repository locator
  name: REPO_LOCATOR
  value: local
- description: Description of the repo
  displayName: Repository description
  name: REPO_DESCRIPTION
  value: "this is a description"
- description: Description of the repo
  displayName: Repository description
  name: REPO_DESCRIPTION
  value: "this is a description"
- description: List of local repos to be added to the virtual repo. Only valid when the repository locator is virtual
  displayName: List local repos in a virtual repo
  name: LIST_REPOS_VIRTUAL
  value: "ops-docker-local,dev-docker-local"
- description: User to run the ansible operator as
  displayName: Operator User
  name: USER
  value: admin
