apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
kind: SecOpsPolicy
metadata:
  name: inter-namespace-comms
spec:
  description: |
    allow the devhub namespace to talk to the VON
    namespace.
  source: /bcgov-devex/lab/blarb1
  destination: /bcgov-devex/lab/blarb2
