---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: networksecuritypolicies.secops.pathfinder.gov.bc.ca
spec:
  group: secops.pathfinder.gov.bc.ca
  names:
    kind: NetworkSecurityPolicy
    listKind: NetworkSecurityPolicyList
    plural: networksecuritypolicies
    singular: networksecuritypolicy
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: externalnetworks.secops.pathfinder.gov.bc.ca
spec:
  group: secops.pathfinder.gov.bc.ca
  names:
    kind: ExternalNetwork
    listKind: ExternalNetworkList
    plural: externalnetworks
    singular: externalnetwork
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: aporetoconsoleaccess.secops.pathfinder.gov.bc.ca
spec:
  group: secops.pathfinder.gov.bc.ca
  names:
    kind: AporetoConsoleAccess
    listKind: AporetoConsoleAccessList
    plural: aporetoconsoleaccess
    singular: aporetoconsoleaccess
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
