apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: artifactorysas.artifactorysa.operators.bcgov
spec:
  group: artifactorysa.operators.bcgov
  names:
    kind: ArtifactorySA
    listKind: ArtifactorySAList
    plural: artifactorysas
    singular: artifactorysa
  scope: Cluster
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true

# Moved to platform ops repository to better track all cluster role creation.
#apiVersion: v1
#kind: ClusterRole
#metadata:
#  name: artifactory-admin
#rules:
#- apiGroups: ["artifactoryrepo.operators.bcgov"]
#  resources: ["artifactoryrepos"]
#  verbs: ["*"]
