---
# vars file for monitoring
sysdig_api_endpoint: https://app.sysdigcloud.com
sysdig_token: "{{ lookup('env', 'SYSDIG_TOKEN') }}"
team: 
  name: test-team
  description: some silly description here 
  namespaces: usage-cost
  users:
   - name: husker@arctiq.ca
     role: ROLE_TEAM_READ 
   - name: shea.stewart+bcgov@arctiq.ca
     role: ROLE_TEAM_MANAGER
   - name: shea.stewart+tester@arctiq.ca
     role: ROLE_TEAM_EDIT


# Available Roles Mapping
# ROLE_TEAM_EDIT
# ROLE_TEAM_STANDARD
# ROLE_TEAM_READ
# ROLE_TEAM_MANAGER
     

