apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: externalnetworks.secops.pathfinder.gov.bc.ca
spec:
  group: secops.pathfinder.gov.bc.ca
  names:
    kind: ExternalNetwork
    listKind: ExternalNetworkList
    plural: externalnetworks
    singular: externalnetwork
    shortNames:
    - en
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
